name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: any
  otp_text_field:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true
