name: otp_text_field_v2
description: A flutter package to create a OTP Text Field widget in your application.
version: 1.0.4
homepage: https://github.com/ahmad-einieh/OTPTextFieldV2

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yaml:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:

