name: otp_text_field_v2
description: A flutter package to create a OTP Text Field widget in your application.
version: 1.0.0
# homepage: 

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yaml:

flutter:

